linuxmint/cinnamon-spices-extensions

- 0dyseus@CinnamonMaximusFork/README.md
- 0dyseus@CinnamonMaximusFork/files/0dyseus@CinnamonMaximusFork/README.md
- 0dyseus@CinnamonTweaks/README.md
- 0dyseus@CinnamonTweaks/files/0dyseus@CinnamonTweaks/README.md
- 0dyseus@WindowDemandsAttentionBehavior/README.md
- 0dyseus@WindowDemandsAttentionBehavior/files/0dyseus@WindowDemandsAttentionBehavior/README.md
- Fixed broken links on READMEs.
> Extensions updates

- 0dyseus@MultiTranslatorExtension/CHANGELOG.md
- 0dyseus@MultiTranslatorExtension/HELP.pug
- 0dyseus@MultiTranslatorExtension/README.md
- 0dyseus@MultiTranslatorExtension/docs/HELP-es.md
- 0dyseus@MultiTranslatorExtension/docs/HELP.md
- 0dyseus@MultiTranslatorExtension/files/0dyseus@MultiTranslatorExtension/HELP.html
- 0dyseus@MultiTranslatorExtension/files/0dyseus@MultiTranslatorExtension/metadata.json
- 0dyseus@MultiTranslatorExtension/files/0dyseus@MultiTranslatorExtension/po/es.po
- 0dyseus@MultiTranslatorExtension/files/0dyseus@MultiTranslatorExtension/po/hr.po
- 0dyseus@MultiTranslatorExtension/files/0dyseus@MultiTranslatorExtension/po/localization-template.pot
- 0dyseus@MultiTranslatorExtension/files/0dyseus@MultiTranslatorExtension/settings.py
- Updated README due to localizations updates.
- Changed the contributors key on the metadata.json file from a string to an array for easier reviewing and better legibility.
- Some code clean up on the settings.py file.
- Added About dialog and direct link to the help file to the main menu on the settings window.
- Added localized help.
> Multi Translator (0dyseus@MultiTranslatorExtension) update

- ShadowParameters@mikhail-ekzi/files/ShadowParameters@mikhail-ekzi/po/ShadowParameters@mikhail-ekzi.pot
- ShadowParameters@mikhail-ekzi/files/ShadowParameters@mikhail-ekzi/po/zh_CN.po
> Add translation support for Custom Shadows

- DesktopCube@yare/files/DesktopCube@yare/po/DesktopCube@yare.pot
- DesktopCube@yare/files/DesktopCube@yare/po/zh_CN.po
> Add translation for Desktop Cube

- workspace-scroller@ori/files/workspace-scroller@ori/po/workspace-scroller@ori.pot
- workspace-scroller@ori/files/workspace-scroller@ori/po/zh_CN.po
> Add translation for Workspace Scroller

- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/smart-panel@mohammad-sn.pot
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/zh_CN.po
> Add translation for Smart Panel

- workspace-grid@daemonl/files/po/workspace-grid@daemonl.pot
- workspace-grid@daemonl/files/po/zh_CN.po
> Add translation for Workspace grid

- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/po/desktop-scroller@ccadeptic23.pot
- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/po/zh_CN.po
> Add translation for Desktop Scroller

- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/po/cinnamon-maximus@fmete.pot
- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/po/zh_CN.po
> Add translation for Cinnamon Maximus

- opacify@anish.org/files/opacify@anish.org/po/opacify@anish.org.pot
- opacify@anish.org/files/opacify@anish.org/po/zh_CN.po
> Add translation for Opacify Windows

- wobbly-windows@mecheye.net/files/wobbly-windows@mecheye.net/po/wobbly-windows@mecheye.net.pot
- wobbly-windows@mecheye.net/files/wobbly-windows@mecheye.net/po/zh_CN.po
> Add translation for Wobbly Windows

- Flipper@connerdev/files/Flipper@connerdev/po/Flipper@connerdev.pot
- Flipper@connerdev/files/Flipper@connerdev/po/zh_CN.po
> Add translation for Flipper

- maximus-cinnamon@mathematical.coffee.gmail.com/files/maximus-cinnamon@mathematical.coffee.gmail.com/po/maximus-cinnamon@mathematical.coffee.gmail.com.pot
- maximus-cinnamon@mathematical.coffee.gmail.com/files/maximus-cinnamon@mathematical.coffee.gmail.com/po/zh_CN.po
@mathematical.coffee.gmail.com
> Add translation for Maximus

- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/blur-overview@nailfarmer.nailfarmer.com.pot
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/zh_CN.po
> Add translation for Blur Overview

- slider@mohammad-sn/files/slider@mohammad-sn/po/slider@mohammad-sn.pot
- slider@mohammad-sn/files/slider@mohammad-sn/po/zh_CN.po
> Add translation for Slider

- Win7AltTab@entelechy/files/Win7AltTab@entelechy/po/Win7AltTab@entelechy.pot
- Win7AltTab@entelechy/files/Win7AltTab@entelechy/po/zh_CN.po
> Add translation for Win7 Alt-Tab

- gTile@shuairan/files/gTile@shuairan/po/gTile@shuairan.pot
- gTile@shuairan/files/gTile@shuairan/po/zh_CN.po
> Add translation for gTile

- 0dyseus@WindowDemandsAttentionBehavior/README.md
- 0dyseus@WindowDemandsAttentionBehavior/docs/HELP-es.md
- 0dyseus@WindowDemandsAttentionBehavior/files/0dyseus@WindowDemandsAttentionBehavior/HELP.html
- 0dyseus@WindowDemandsAttentionBehavior/files/0dyseus@WindowDemandsAttentionBehavior/extension.js
- 0dyseus@WindowDemandsAttentionBehavior/files/0dyseus@WindowDemandsAttentionBehavior/metadata.json
- 0dyseus@WindowDemandsAttentionBehavior/files/0dyseus@WindowDemandsAttentionBehavior/po/0dyseus@WindowDemandsAttentionBehavior.json
- 0dyseus@WindowDemandsAttentionBehavior/files/0dyseus@WindowDemandsAttentionBehavior/po/0dyseus@WindowDemandsAttentionBehavior.pot
- 0dyseus@WindowDemandsAttentionBehavior/files/0dyseus@WindowDemandsAttentionBehavior/po/zh_CN.po
- Added Chinese localization. Thanks to [giwhub](https://github.com/giwhub).
- Changed contributors key on metadata.json file from a string to an array for better readability.
- Changed cinnamon-version key on metadata.json file to support Cinnamon 3.4.
- Corrected a typo on the localized help file.
> Window demands attention behavior (0dyseus@WindowDemandsAttentionBehavior) update

- 0dyseus@CinnamonMaximusFork/README.md
- 0dyseus@CinnamonMaximusFork/docs/HELP-es.md
- 0dyseus@CinnamonMaximusFork/files/0dyseus@CinnamonMaximusFork/HELP.html
- 0dyseus@CinnamonMaximusFork/files/0dyseus@CinnamonMaximusFork/metadata.json
- 0dyseus@CinnamonMaximusFork/files/0dyseus@CinnamonMaximusFork/po/zh_CN.po
- Changed contributors key on metadata.json file from a string to an array for better readability.
- Changed cinnamon-version key on metadata.json file to support Cinnamon 3.4.
- Corrected a typo on the localized help file.
> Cinnamon Maximus (Fork by Odyseus) (0dyseus@CinnamonMaximusFork) update

- Flipper@connerdev/info.json
- blur-overview@nailfarmer.nailfarmer.com/info.json
- gnome2alttab@savagetiger.org/info.json
- maximus-cinnamon@mathematical.coffee.gmail.com/info.json
- opacify@anish.org/info.json
- panel-span@weston_schmidt.alumni.purdue.edu/info.json
Flipper@connerdev -> @ConnerHansen
blur-overview@nailfarmer.nailfarmer.com -> @nailfarmer
gnome2alttab@savagetiger.org -> @SavageTiger
maximus-cinnamon@mathematical.coffee.gmail.com -> @mathematicalcoffee
opacify@anish.org -> @AnishN
panel-span@weston_schmidt.alumni.purdue.edu -> @schmidtw
> Use correct GitHub name of author in info.json

- CinnaDockPlus@entelechy/info.json
- Win7AltTab@entelechy/info.json
- wobbly-windows@mecheye.net/info.json
- workspace-grid@daemonl/info.json
Set author to none because abandoned, nonexistent user or donated.
@entelechy
@daemonl
@mecheye.net
> 4 applets: set author to none

- workspace-grid@daemonl/files/metadata.json
Hi,
I have seen no issues with Cinnamon 3.2, so it may be flagged as compatible ?
Thanks for all the hard work !
> workspace-grid@daemonl: Flag as compatible with Cinnamon 3.2

- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/extension.js
- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/metadata.json
- Add version 3.2 and 3.4 in metadata.json
- Fix redeclaration of variable i
> cinnamon-maximus@fmete: Make it compatible with cinnamon 3.4

- transparent-panels@germanfr/files/transparent-panels@germanfr/po/tr.po
transparent-panels@germanfr: Added tr.po
> transparent-panels@germanfr: Added tr.po

- 0dyseus@CinnamonTweaks/files/0dyseus@CinnamonTweaks/HELP.html
- 0dyseus@CinnamonTweaks/files/0dyseus@CinnamonTweaks/metadata.json
- 0dyseus@CinnamonTweaks/files/0dyseus@CinnamonTweaks/po/0dyseus@CinnamonTweaks.pot
- 0dyseus@CinnamonTweaks/files/0dyseus@CinnamonTweaks/po/cs.po
- 0dyseus@CinnamonTweaks/files/0dyseus@CinnamonTweaks/po/da.po
- 0dyseus@CinnamonTweaks/files/0dyseus@CinnamonTweaks/po/es.po
- 0dyseus@CinnamonTweaks/files/0dyseus@CinnamonTweaks/po/hr.po
- 0dyseus@CinnamonTweaks/files/0dyseus@CinnamonTweaks/po/sv.po
- 0dyseus@CinnamonTweaks/files/0dyseus@CinnamonTweaks/po/zh_CN.po
- Updated localization template, localizations and help file.
> Cinnamon Tweaks (0dyseus@CinnamonTweaks) update

- DesktopCube@yare/files/DesktopCube@yare/po/tr.po
> DesktopCube@yare: add tr.po

- .github/validate-spices-repo
- README.md
- cinnamon-spices-makepot
- validate-spice
see README for hot to use this scripts
> add validate-spice and cinnamon-json-makepot scripts

- Flipper@connerdev/files/Flipper@connerdev/metadata.json
This adds compatibility for Cinnamon 3.6 series to this extension.
> Flipper@connverdev: Add compatibility for Cinnamon 3.6 series

- gTile@shuairan/files/gTile@shuairan/po/sv.po
> gTile@shuairan: add sv.po

- transparent-panels@germanfr/files/transparent-panels@germanfr/extension.js
- transparent-panels@germanfr/files/transparent-panels@germanfr/metadata.json
> transparent-panels@germanfr: Fix for Cinnamon 3.8

- ShadowParameters@mikhail-ekzi/files/ShadowParameters@mikhail-ekzi/po/tr.po
ShadowParameters@mikhail-ekzi: add tr.po
> ShadowParameters@mikhail-ekzi: add tr.po

- transparent-panels@germanfr/files/transparent-panels@germanfr/README.md
- transparent-panels@germanfr/files/transparent-panels@germanfr/extension.js
- transparent-panels@germanfr/files/transparent-panels@germanfr/filter.js
- transparent-panels@germanfr/files/transparent-panels@germanfr/po/da.po
- transparent-panels@germanfr/files/transparent-panels@germanfr/po/es.po
- transparent-panels@germanfr/files/transparent-panels@germanfr/po/transparent-panels@germanfr.pot
- transparent-panels@germanfr/files/transparent-panels@germanfr/settings-schema.json
- transparent-panels@germanfr/files/transparent-panels@germanfr/stylesheet.css
Changelog at: https://github.com/germanfr/cinnamon-transparent-panels/commits/master
> Update Transparent panels v3.6 (transparent-panels@germanfr)

- watermark@germanfr/files/watermark@germanfr/extension.js
- watermark@germanfr/files/watermark@germanfr/po/es.po
- watermark@germanfr/files/watermark@germanfr/po/watermark@germanfr.pot
- watermark@germanfr/files/watermark@germanfr/settings-schema.json
Changelog at: https://github.com/germanfr/watermark-cinnamon/commits/master
> Update Watermark v3.6 (watermark@germanfr)

- ShadowParameters@mikhail-ekzi/info.json
add license info for ShadowParameters@mikhail-ekzi
> add license info for ShadowParameters@mikhail-ekzi

- watermark@germanfr/files/watermark@germanfr/metadata.json
Changelog at: https://github.com/germanfr/watermark-cinnamon/commits/master
> Update Watermark v3.8 (watermark@germanfr)

- transparent-panels@germanfr/files/transparent-panels@germanfr/README.md
- transparent-panels@germanfr/files/transparent-panels@germanfr/extension.js
- transparent-panels@germanfr/files/transparent-panels@germanfr/metadata.json
- transparent-panels@germanfr/files/transparent-panels@germanfr/po/da.po
- transparent-panels@germanfr/files/transparent-panels@germanfr/po/es.po
- transparent-panels@germanfr/files/transparent-panels@germanfr/po/transparent-panels@germanfr.pot
- transparent-panels@germanfr/files/transparent-panels@germanfr/settings-schema.json
Changelog at: https://github.com/germanfr/cinnamon-transparent-panels/commits/master
> Update Transparent panels v3.8 (transparent-panels@germanfr)

- desktop-icons-per-workspace@cardsurf/README.md
Added limitations to the README.md file.
> [desktop-icons-per-workspace@cardsurf] Added limitations

- Win7AltTab@entelechy/files/Win7AltTab@entelechy/extension.js
> Win7AltTab@entelechy: Fix for Cinnamon 3.8

- .gitignore
- README.md
- gulpfile.js
- package-lock.json
- package.json
See https://github.com/linuxmint/cinnamon-spices-applets/pull/2075
> repo: Add a utility for reloading extensions on code change

- gTile@shuairan/files/gTile@shuairan/extension.js
This commit enables gTile to deal with multiple panels at any screen
edge or monitor.
> gTile@shuairan: Deal with complex panel configurations

- workspace-scroller@ori/files/workspace-scroller@ori/po/tr.po
workspace-scroller@ori: add tr.po
> workspace-scroller@ori: add tr.po

- gTile@shuairan/files/gTile@shuairan/po/tr.po
> gTile@shuairan: add tr.po

- transparent-panels@germanfr/files/transparent-panels@germanfr/po/tr.po
Changelog at: https://github.com/germanfr/cinnamon-transparent-panels/commits/master
> Update Transparent panels v4.0~20181106 (transparent-panels@germanfr)

- gTile@shuairan/files/gTile@shuairan/metadata.json
> gTile@shuairan: Update version compatibility

- DesktopCube@yare/files/DesktopCube@yare/extension.js
- DesktopCube@yare/files/DesktopCube@yare/po/DesktopCube@yare.pot
- DesktopCube@yare/files/DesktopCube@yare/po/fr.po
- DesktopCube@yare/files/DesktopCube@yare/settings-schema.json
Hi,
This is my part to help to solve issue #208.
Now a button in the DesktopCube@yare settings allows to access to the Workspaces module of Cinnamon Settings.
I also modified the .pot file and added the fr.po file.
Can you merge this branch with your master one, please?
Best regards.
Claudiux
> DesktopCube@yare: Button to access to the Cinnamon Settings Workspaces module.

- workspace-grid@daemonl/files/workspace-grid@daemonl/po/workspace-grid@daemonl.pot
Dutch translation off Workspace grid
> Workspace grid nl.po

- desktop-icons-per-workspace@cardsurf/files/desktop-icons-per-workspace@cardsurf/metadata.json
- desktop-icons-per-workspace@cardsurf/files/desktop-icons-per-workspace@cardsurf/shellUtils.js
Replaced tempfile command with mktemp
> [desktop-icons-per-workspace@cardsurf] Use mktemp command

- watermark@germanfr/files/watermark@germanfr/LICENSE
- watermark@germanfr/files/watermark@germanfr/metadata.json
- watermark@germanfr/files/watermark@germanfr/po/fr.po
Changelog at: https://github.com/germanfr/watermark-cinnamon/commits/master
> Update Watermark v4.2-20190710 (watermark@germanfr)

- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/extension.js
- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/metadata.json
Changes:
- Fixed the error when the undecorate tile option is enabled
- Avoid the warnings at disabling of the extension
- Fixed the coding style
- Updated the compatible versions of the cinnamon
> maximus@fmete: update to make the extension working

- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/po/tr.po
cinnamon-maximus@fmete: add tr.po
> cinnamon-maximus@fmete: add tr.po

- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/tr.po
blur-overview@nailfarmer.nailfarmer.com: add tr.po
> blur-overview@nailfarmer.nailfarmer.com: add tr.po

- DesktopCube@yare/files/DesktopCube@yare/metadata.json
> [DesktopCube@yare] Now compatible with Cinnamon 4.4

- opacify@anish.org/files/opacify@anish.org/po/tr.po
> opacify@anish.org: add tr.po

- rnbdsh@negateWindow/files/rnbdsh@negateWindow/metadata.json
- rnbdsh@negateWindow/files/rnbdsh@negateWindow/po/rnbdsh@negateWindow.pot
- rnbdsh@negateWindow/files/rnbdsh@negateWindow/po/tr.po
add pot file
add tr.po file
add support for 4.4 (any issue on Cinnamon 4.4)
> rnbdsh@negateWindow: Add pot and tr.po file, support for 4.4

- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/metadata.json
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/tr:po
add tr.po
Add support for 4.4 (working with any issue on Cinnamon 4.4)
> smart-panel@mohammad-sn: add tr.po, support for 4.4

- watermark@germanfr/files/watermark@germanfr/po/sv.po
> watermark@germanfr: add sv.po

- transparent-panels@germanfr/files/transparent-panels@germanfr/po/sv.po
> transparent-panels@germanfr: add sv.po

- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/metadata.json
- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/po/sv.po
Add Swedish translation and make compatible with Cinnamon 4.4
> cinnamon-maximus@fmete: add sv.po

- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/sv.po
> smart-panel@mohammad-sn: add sv.po

- gTile@shuairan/files/gTile@shuairan/po/sv.po
Update Swedish translation from POT
> gTile@shuairan: Update sv.po

- workspace-scroller@ori/files/workspace-scroller@ori/metadata.json
- workspace-scroller@ori/files/workspace-scroller@ori/po/sv.po
Add Swedish translation and make compatible with Cinnamon 4.4
> workspace-scroller@ori: add sv.po

- transparent-panels@germanfr/files/transparent-panels@germanfr/metadata.json
> transparent-panels: cinnamon 4.6 compatible

- gTile@shuairan/files/gTile@shuairan/extension.js
> Add fallback for calculating panel height for old versions of cinnamon.

- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/extension.js
- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/metadata.json
- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/settings-schema.json
1. use get_wm_class_instance as application name
2. use template strings instead concatenations strings and variables
3. rename the blacklist to the ignore list due by better meanful
4. add the auto undecoration list
> cinnamon-maximus@fmete: various improvements

- Win7AltTab@entelechy/files/Win7AltTab@entelechy/po/hu.po
- gTile@shuairan/files/gTile@shuairan/po/hu.po
- transparent-panels@germanfr/files/transparent-panels@germanfr/po/hu.po
I added the Hungarian translation to some extensions.
> New Hungarian translations

- gTile@shuairan/files/gTile@shuairan/po/sv.po
> gTile@shuairan: Update sv.ts

- opacify@anish.org/files/opacify@anish.org/extension.js
> opacify@anish.org: End of drag transition time is start of drag transition time #297 FIX

- Flipper@connerdev/files/Flipper@connerdev/po/tr.po
Flipper@connerdev.pot: Added tr.po
> Flipper@connerdev.pot: Added tr.po

- Flipper@connerdev/files/Flipper@connerdev/metadata.json
Closes https://github.com/linuxmint/cinnamon-spices-extensions/issues/195
> Flipper@connerdev: Update cinnamon-versions flag

- DesktopCube@yare/files/DesktopCube@yare/po/hu.po
- Flipper@connerdev/files/Flipper@connerdev/po/hu.po
- SanitizeXsessionErrors@claudiux/files/SanitizeXsessionErrors@claudiux/po/hu.po
- ShadowParameters@mikhail-ekzi/files/ShadowParameters@mikhail-ekzi/po/hu.po
- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/po/hu.po
- desktop-icons-per-workspace@cardsurf/files/desktop-icons-per-workspace@cardsurf/po/hu.po
- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/po/hu.po
- opacify@anish.org/files/opacify@anish.org/po/hu.po
- rnbdsh@negateWindow/files/rnbdsh@negateWindow/po/hu.po
- slider@mohammad-sn/files/slider@mohammad-sn/po/hu.po
- watermark@germanfr/files/watermark@germanfr/po/hu.po
- wobbly-windows@mecheye.net/files/wobbly-windows@mecheye.net/po/hu.po
Hello,
these are the Hungarian translation files for the remaining, not yet translated spices extensions.
> Hungarian translation for spices extensions

- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/extension.js
Properly separate the list of ignored/auto-undecorated apps.
Fixes #329
***
I'm not sure exactly who is responsible for the extensions or for approving PRs. Tagging @brownsr @NikoKrause
> cinnamon-maximus@fmete: Properly separate app lists

- back-to-monitor@nathan818fr/files/back-to-monitor@nathan818fr/po/pt_BR.po
Thank you for your advice https://github.com/linuxmint/cinnamon-spices-extensions/pull/361#issuecomment-980760223 @brownsr
> back-to-monitor@nathan818fr: add pt_BR.po

- cinTile@tabcodes/files/cinTile@tabcodes/extension.js
Code adapted from [this PR](https://github.com/linuxmint/cinnamon-spices-extensions/pull/363) by @mtwebster -- fixes handling positioning/sizing for client-decorated windows.
> cinTile@tabcodes: Fix cinTile csd handling

- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/extension.js
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/metadata.json
@mohammad-sn 
This fix simply allows the extension to start, I did not test any of the features because I'm not using the extension
> smart-panel@mohammad-sn - Fix smart-panel not starting in 5.4

- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/extension.js
I have tested this OK on Linux Mint 19.3, 20.3 and 21 beta.
> make cinnamon-maximus@fmete work with Cinnamon 5.4 (fixes issue #385)

- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/ko.po
- smart-panel@mohammad-sn extension
> Add Korean translation

- transparent-panels@germanfr/files/transparent-panels@germanfr/po/ja.po
Japanese translation for transparent-panels.
> transparent-panels: add & finish ja.po translation

- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/po/ja.po
Japanese translation for cinnamon-maximus.
> cinnamon-maximus: add  ja.po

- gTile@shuairan/files/gTile@shuairan/po/ja.po
Japanese translation included (Fixed version of the previous pull request).
> gTile: add ja.po

- compiz-windows-effect@hermes83.github.com/README.md
- compiz-windows-effect@hermes83.github.com/files/compiz-windows-effect@hermes83.github.com/extension.js
- compiz-windows-effect@hermes83.github.com/files/compiz-windows-effect@hermes83.github.com/metadata.json
- compiz-windows-effect@hermes83.github.com/files/compiz-windows-effect@hermes83.github.com/po/it.po
fix readme screenshot, fix italian transation and minor changes
> fix readme, fix transation and minor changes

- mouse-shake-zoom@rcalixte/files/mouse-shake-zoom@rcalixte/5.6/extension.js
Fixes #454.
@rcalixte can you review the changes?
> mouse-shake-zoom@rcalixte: restore cursor size even if the size was modified

- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/extension.js
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/pt_BR.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/settings-schema.json
Added checkbox to control the notification that appears on the top left corner when changing workspaces.
Related to issue #461.
@mohammad-sn
> smart-panel@mohammad-sn: checkbox for top left notification on workspace change

- transparent-panels@germanfr/files/transparent-panels@germanfr/po/uk.po
Please consider adding Ukrainian translation
> Add Ukrainian translation for transparent-panels

- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/uk.po
Please consider adding Ukrainian translation
> Add Ukrainian translation for smart-panel

- compiz-windows-effect@hermes83.github.com/files/compiz-windows-effect@hermes83.github.com/po/ru.po
Small fix `1`  word, for better any peoples understanding
> better translate to 'wobbly' word

- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/it.po
Hi,
I reviewed and updated the Italian translation for the extension smart-panel@mohammad-sn :)
Have a nice day
> Updates Italian translation for smart-panel@mohammad-sn

- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/hu.po
I updated the only out of date translation for Hungarian
> Updated Hungarian translation for cinnamon spices extensions

- transparent-panels@germanfr/files/transparent-panels@germanfr/extension.js
cc @germanfr
Following https://github.com/linuxmint/cinnamon-spices-extensions/pull/546
>  transparent-panels@germanfr: properly update on monitors changed

- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/po/cinnamon-dynamic-wallpaper@TobiZog.pot
These are the strings exported from the Glade file. If translation works in the UI, we can change the makepot script to make future automation easier. This is the first extension to use a Glade file but if it works, we can make all the scripting changes to support it.
cc @TobiZog
> cinnamon-dynamic-wallpaper@TobiZog: Add Glade strings to translation template

- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/po/cinnamon-dynamic-wallpaper@TobiZog.pot
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/po/es.po
- cinnamon-spices-makepot
New features:
* Automatic updating of translations when the template is updated
* Updated header format
* Add translation support for Glade files and shell scripts
> Rewrite cinnamon-spices-makepot:

- cinnamon-dynamic-wallpaper@TobiZog/.gitignore
- cinnamon-dynamic-wallpaper@TobiZog/CHANGELOG
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/5.4/extension.js
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/5.4/res/preferences.glade
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/5.4/src/main.py
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/5.4/src/model/main_view_model.py
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/5.4/src/service/cinnamon_pref_handler.py
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/5.4/src/view/main_window.py
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/metadata.json
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/po/cinnamon-dynamic-wallpaper@TobiZog.pot
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/po/de.po
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/po/nl.po
Translation support for Dutch, German and Spanish (thanks to @rcalixte)
> Cinnamon Dynamic Wallpaper v.2.3

- cinnamon-dynamic-wallpaper@TobiZog/.gitignore
- cinnamon-dynamic-wallpaper@TobiZog/CHANGELOG
- cinnamon-dynamic-wallpaper@TobiZog/README.md
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/5.4/extension.js
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/5.4/res/preferences.glade
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/5.4/settings-schema.json
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/5.4/src/main.py
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/5.4/src/model/main_view_model.py
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/5.4/src/service/cinnamon_pref_handler.py
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/5.4/src/service/suntimes.py
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/5.4/src/view/main_window.py
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/metadata.json
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/po/cinnamon-dynamic-wallpaper@TobiZog.pot
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/po/de.po
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/po/es.po
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/po/hu.po
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/po/ru.po
- Adding Login window support
- Adding Russian translation (Thanks to blogdron)
- Adding Hungarian translation (Thanks to vajdao)
- Bugfix: Time period calculation on locations near the dateline, like Japan
> Cinnamon Dynamic Wallpaper v.2.4

- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/po/ru.po
Two new lines translated and some translated lines corrected
> cinnamon-dynamic-wallpaper@TobiZog: Russian translation update

- horizontal-osd@berk-karaal/files/horizontal-osd@berk-karaal/po/fr.po
- horizontal-osd@berk-karaal/files/horizontal-osd@berk-karaal/po/horizontal-osd@berk-karaal.pot
@berk-karaal
This PR creates the po folder containing the pot file and fr.po file.
> [horizontal-osd@berk-karaal] Allows translations and adds French translation

- cinnamon-dynamic-wallpaper@TobiZog/CHANGELOG
- cinnamon-spices-makepot
cc @TobiZog (if you want to also correct the CHANGELOG on your mirror repository)
> Update cinnamon-spices-makepot and correct CHANGELOG attribution

- adjacent-windows@klangman/CHANGELOG.md
- adjacent-windows@klangman/README.md
- adjacent-windows@klangman/files/adjacent-windows@klangman/5.4/extension.js
- adjacent-windows@klangman/files/adjacent-windows@klangman/5.4/settings-schema.json
- adjacent-windows@klangman/files/adjacent-windows@klangman/metadata.json
- adjacent-windows@klangman/files/adjacent-windows@klangman/po/adjacent-windows@klangman.pot
- adjacent-windows@klangman/files/adjacent-windows@klangman/po/es.po
1. Added two configuration options to offer some advanced controls over how the algorithm works when using the "Closest with a visible corner" setting.
2. Moved files to a 5.4 directory as an added protection ensuring that the extension is only used in Cinnamon 5.4 or higher.
3. Fixed some typos in the README.md file.
> [adjacent-windows@klangman] Add two algorithm tuning options

- back-to-monitor@nathan818fr/files/back-to-monitor@nathan818fr/po/zh.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/zh_CN.po
* back-to-monitor@nathan818fr
* blur-overview@nailfarmer.nailfarmer.com
> Add Chinese Translation

- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/po/zh.po
- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/po/zh.po
- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/po/zh_CN.po
- compiz-windows-effect@hermes83.github.com/files/compiz-windows-effect@hermes83.github.com/po/zh.po
* cinnamon-dynamic-wallpaper@TobiZog
* cinnamon-maximus@fmete
* compiz-windows-effect@hermes83.github.com
> Update Chinese translation

- adjacent-windows@klangman/files/adjacent-windows@klangman/po/eu.po
- adjacent-windows@klangman: Added Basque translation
> adjacent-windows@klangman: Added Basque translation

- focus-new-window@mdpenguin/files/focus-new-window@mdpenguin/extension.js
Fix disconnection try on possibly null signal id values
I noticed the following issue while analyzing Cinnamon's logs:
cc @mdpenguin
> focus-new-window@mdpenguin: Fix disconnection try on possibly null signal id values

- focus-new-window@mdpenguin/files/focus-new-window@mdpenguin/metadata.json
> focus-new-window@mdpenguin: Update metadata for Cinnamon versions

- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/po/de.po
- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/settings-schema.json
Add dependencies to make settings more comprehensible:
* keybinding for hotkey only if hotkey is enabled
* ignore list only if ignore is enabled
* auto-undecorate list only if auto-undecorate is enabled
> cinnamon-maximus@fmete: Add dependencies to settings

- adjacent-windows@klangman/files/adjacent-windows@klangman/5.4/extension.js
- adjacent-windows@klangman/files/adjacent-windows@klangman/5.4/settings-schema.json
- adjacent-windows@klangman/files/adjacent-windows@klangman/metadata.json
> adjacent-windows@klangman: Add option to  warp cursor to the center of the focused window

- DesktopCube@yare/files/DesktopCube@yare/po/ca.po
- Flipper@connerdev/files/Flipper@connerdev/po/ca.po
- SanitizeXsessionErrors@claudiux/files/SanitizeXsessionErrors@claudiux/po/ca.po
- ShadowParameters@mikhail-ekzi/files/ShadowParameters@mikhail-ekzi/po/ca.po
- adjacent-windows@klangman/files/adjacent-windows@klangman/po/ca.po
- back-to-monitor@nathan818fr/files/back-to-monitor@nathan818fr/po/ca.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/ca.po
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/po/ca.po
- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/po/ca.po
- compiz-windows-effect@hermes83.github.com/files/compiz-windows-effect@hermes83.github.com/po/ca.po
- desktop-icons-per-workspace@cardsurf/files/desktop-icons-per-workspace@cardsurf/po/ca.po
- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/po/ca.po
- extra-panel-settings@gr3q/files/extra-panel-settings@gr3q/po/ca.po
- focus-new-window@mdpenguin/files/focus-new-window@mdpenguin/po/ca.po
- gTile@shuairan/files/gTile@shuairan/po/ca.po
- horizontal-osd@berk-karaal/files/horizontal-osd@berk-karaal/po/ca.po
- mouse-click-effects@anaximeno/files/mouse-click-effects@anaximeno/po/ca.po
- mouse-shake-zoom@rcalixte/files/mouse-shake-zoom@rcalixte/po/ca.po
- opacify@anish.org/files/opacify@anish.org/po/ca.po
- opacity-slider@neatnit/files/opacity-slider@neatnit/po/ca.po
- rnbdsh@negateWindow/files/rnbdsh@negateWindow/po/ca.po
- slider@mohammad-sn/files/slider@mohammad-sn/po/ca.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/ca.po
- transparent-panels-reloaded@marcelovbcfilho/files/transparent-panels-reloaded@marcelovbcfilho/po/ca.po
- transparent-panels@germanfr/files/transparent-panels@germanfr/po/ca.po
- user-shadows@nathan818fr/files/user-shadows@nathan818fr/po/ca.po
- watermark@germanfr/files/watermark@germanfr/po/ca.po
- wobbly-windows@mecheye.net/files/wobbly-windows@mecheye.net/po/ca.po
- workspace-scroller@ori/files/workspace-scroller@ori/po/ca.po
* adjacent-windows@klangman
* back-to-monitor@nathan818fr
* blur-overview@nailfarmer.nailfarmer.com
* cinnamon-dynamic-wallpaper@TobiZog
* cinnamon-maximus@fmete
* compiz-windows-effect@hermes83.github.com
* DesktopCube@yare
* desktop-icons-per-workspace@cardsurf
* desktop-scroller@ccadeptic23
* extra-panel-settings@gr3q
* Flipper@connerdev
* focus-new-window@mdpenguin
* gTile@shuairan
* horizontal-osd@berk-karaal
* mouse-click-effects@anaximeno
* mouse-shake-zoom@rcalixte
* opacify@anish.org
* opacity-slider@neatnit
* rnbdsh@negateWindow
* SanitizeXsessionErrors@claudiux
* ShadowParameters@mikhail-ekzi
* slider@mohammad-sn
* smart-panel@mohammad-sn
* transparent-panels@germanfr
* transparent-panels-reloaded@marcelovbcfilho
* user-shadows@nathan818fr
* watermark@germanfr
* …
> Add Catalan translations

- adjacent-windows@klangman/files/adjacent-windows@klangman/po/fi.po
- back-to-monitor@nathan818fr/files/back-to-monitor@nathan818fr/po/fi.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/fi.po
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/po/fi.po
- compiz-windows-effect@hermes83.github.com/files/compiz-windows-effect@hermes83.github.com/po/fi.po
- focus-new-window@mdpenguin/files/focus-new-window@mdpenguin/po/fi.po
- gTile@shuairan/files/gTile@shuairan/po/fi.po
- mouse-shake-zoom@rcalixte/files/mouse-shake-zoom@rcalixte/po/fi.po
- opacify@anish.org/files/opacify@anish.org/po/fi.po
- opacity-slider@neatnit/files/opacity-slider@neatnit/po/fi.po
- rnbdsh@negateWindow/files/rnbdsh@negateWindow/po/fi.po
- transparent-panels-reloaded@marcelovbcfilho/files/transparent-panels-reloaded@marcelovbcfilho/po/fi.po
- transparent-panels@germanfr/files/transparent-panels@germanfr/po/fi.po
- watermark@germanfr/files/watermark@germanfr/po/fi.po
New translations and updates in Finnish
> Finnish translation updates

- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/fi.po
- opacify@anish.org/files/opacify@anish.org/po/fi.po
- opacity-slider@neatnit/files/opacity-slider@neatnit/po/fi.po
- transparent-panels-reloaded@marcelovbcfilho/files/transparent-panels-reloaded@marcelovbcfilho/po/fi.po
- watermark@germanfr/files/watermark@germanfr/po/fi.po
I had made a translation mistake in one word.
> Update fi.po. Incorrect phrase corrected

- gTile@shuairan/files/gTile@shuairan/po/ko.po
Add Korean translation for gTile@shuairan
> Add Korean translation for gTile@shuairan

- Flipper@connerdev/CHANGELOG.md
- Flipper@connerdev/files/Flipper@connerdev/5.4/extension.js
- Flipper@connerdev/files/Flipper@connerdev/5.4/settings-schema.json
- Flipper@connerdev/files/Flipper@connerdev/metadata.json
- Flipper@connerdev/files/Flipper@connerdev/po/Flipper@connerdev.pot
- Flipper@connerdev/files/Flipper@connerdev/po/ca.po
- Flipper@connerdev/files/Flipper@connerdev/po/da.po
- Flipper@connerdev/files/Flipper@connerdev/po/de.po
- Flipper@connerdev/files/Flipper@connerdev/po/es.po
- Flipper@connerdev/files/Flipper@connerdev/po/eu.po
- Flipper@connerdev/files/Flipper@connerdev/po/hu.po
- Flipper@connerdev/files/Flipper@connerdev/po/it.po
- Flipper@connerdev/files/Flipper@connerdev/po/nl.po
- Flipper@connerdev/files/Flipper@connerdev/po/pt_BR.po
- Flipper@connerdev/files/Flipper@connerdev/po/ro.po
- Flipper@connerdev/files/Flipper@connerdev/po/ru.po
- Flipper@connerdev/files/Flipper@connerdev/po/tr.po
- Flipper@connerdev/files/Flipper@connerdev/po/zh_CN.po
- Flipper@connerdev/info.json
1. Fix the panels showing up in an incorrect location when animating (or when holing Ctrl+Alt after a workspace switch), but I still see occasional panel painting issues.
2. Added a new setting option to disable showing the panels when animating (as a way to avoid any panel animation issues you might be having)
3. Changed the workspace switch OSD to only show after the animation so that there is no odd OSD artifacts while animating
4. Changed author to myself since the extension has no maintainer currently
> [Flipper@connerdev] version 1.0.3

- wobbly-windows@mecheye.net/files/wobbly-windows@mecheye.net/extension.js
I think will fix the graphical artifacts that this extension leaves behind when running on Mint 20.1+. I tested on Mint21 and I don't see any issues. Also fixed some exceptions I spotted in the xsession_errors file.
> [wobbly-windows@mecheye.net] Fix graphical artifacts using Mint20.1+

- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/extension.js
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/metadata.json
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/blur-overview@nailfarmer.nailfarmer.com.pot
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/ca.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/da.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/de.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/es.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/eu.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/fi.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/hu.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/it.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/nl.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/pt_BR.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/ro.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/ru.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/tr.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/zh_CN.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/settings-schema.json
1. Fix to work with Mint 20+ (tested Mint20.3 and Mint22)
2. Changed the config slider to be a percentage
3. Clarified the wording so that it makes it a bit more clear that this really is a dimming effect not a blur effect
> [blur-overview@nailfarmer.nailfarmer.com] Fix for Mint 20+

- CinnamonBurnMyWindows@klangman/CHANGELOG.md
- CinnamonBurnMyWindows@klangman/README.md
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/6.2/extension.js
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/metadata.json
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/CinnamonBurnMyWindows@klangman.pot
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/ca.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/es.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/fr.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/nl.po
The doom effect was not being added to the randomized list of effects when the config option was enabled, this fix will properly add the doom effect to the list of options for random selection.
> [CinnamonBurnMyWindows@klangman] Fix doom effect randomization

- mouse-click-effects@anaximeno/files/mouse-click-effects@anaximeno/5.4/extension.js
- mouse-click-effects@anaximeno/files/mouse-click-effects@anaximeno/5.4/mouseMovementTracker.js
- mouse-click-effects@anaximeno/files/mouse-click-effects@anaximeno/metadata.json
partial fix for https://github.com/linuxmint/cinnamon-spices-extensions/issues/749
> mouse-click-effects@anaximeno: Fix persistent movement tracking interfering with DND operations

- mouse-click-effects@anaximeno/files/mouse-click-effects@anaximeno/5.4/extension.js
- mouse-click-effects@anaximeno/files/mouse-click-effects@anaximeno/5.4/mouseMovementTracker.js
- mouse-click-effects@anaximeno/files/mouse-click-effects@anaximeno/metadata.json
Add support for deactivate in fullscreen to the pointer movement tracker
> mouse-click-effects@anaximeno: Version 1.0.3

- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/fi.po
- CinnamonMagicLamp@klangman/files/CinnamonMagicLamp@klangman/po/fi.po
- DesktopCube@yare/files/DesktopCube@yare/po/fi.po
- Flipper@connerdev/files/Flipper@connerdev/po/fi.po
- ShadowParameters@mikhail-ekzi/files/ShadowParameters@mikhail-ekzi/po/fi.po
- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/po/fi.po
- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/po/fi.po
- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/po/fi.po
- mouse-click-effects@anaximeno/files/mouse-click-effects@anaximeno/po/fi.po
- slider@mohammad-sn/files/slider@mohammad-sn/po/fi.po
- user-shadows@nathan818fr/files/user-shadows@nathan818fr/po/fi.po
- wobbly-windows@mecheye.net/files/wobbly-windows@mecheye.net/po/fi.po
- workspace-scroller@ori/files/workspace-scroller@ori/po/fi.po
New Finnish translations and updated new lines for older translations.
> New Finnish translations and updates

- blur-overview@nailfarmer.nailfarmer.com/CHANGELOG.md
- blur-overview@nailfarmer.nailfarmer.com/README.md
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/extension.js
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/metadata.json
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/blur-overview@nailfarmer.nailfarmer.com.pot
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/ca.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/da.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/de.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/es.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/eu.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/fi.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/hu.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/it.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/nl.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/pt_BR.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/ro.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/ru.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/tr.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/zh_CN.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/settings-schema.json
- blur-overview@nailfarmer.nailfarmer.com/info.json
Restore the Blur Effect which was removed in 2021 for no reason that I can discern 
Added a config option to disable the blur effect
Added README and CHANGELOG
Added myself as maintainer since it's currently without one
> [blur-overview@nailfarmer.nailfarmer.com] Restore blur effect

- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/ca.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/ca.po
* blur-overview@nailfarmer.nailfarmer.com
* CinnamonBurnMyWindows@klangman
> Update Catalan translations

- CinnamonMagicLamp@klangman/CHANGELOG.md
- CinnamonMagicLamp@klangman/files/CinnamonMagicLamp@klangman/5.6/extension.js
- CinnamonMagicLamp@klangman/files/CinnamonMagicLamp@klangman/5.6/settings-schema.json
- CinnamonMagicLamp@klangman/files/CinnamonMagicLamp@klangman/metadata.json
- CinnamonMagicLamp@klangman/files/CinnamonMagicLamp@klangman/po/CinnamonMagicLamp@klangman.pot
- CinnamonMagicLamp@klangman/files/CinnamonMagicLamp@klangman/po/ca.po
- CinnamonMagicLamp@klangman/files/CinnamonMagicLamp@klangman/po/es.po
- CinnamonMagicLamp@klangman/files/CinnamonMagicLamp@klangman/po/fi.po
- CinnamonMagicLamp@klangman/files/CinnamonMagicLamp@klangman/po/hu.po
- CinnamonMagicLamp@klangman/files/CinnamonMagicLamp@klangman/po/nl.po
- CinnamonMagicLamp@klangman/files/CinnamonMagicLamp@klangman/po/pt.po
1. Added new effect options that all you to use a random effect or use different effects for minimizing and unminimizing
2. Changed the configuration controls for "effect duration" and X/Y tiles to be a slider-bar rather than a spin button
> [CinnamonMagicLamp@klangman] Add new random and action specific options

- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/README
- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/extension.js
- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/metadata.json
- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/po/ca.po
- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/po/da.po
- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/po/de.po
- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/po/desktop-scroller@ccadeptic23.pot
- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/po/es.po
- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/po/eu.po
- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/po/fi.po
- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/po/hu.po
- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/po/it.po
- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/po/nl.po
- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/po/pt_BR.po
- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/po/ro.po
- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/po/ru.po
- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/po/zh_CN.po
- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/settings-schema.json
Added the ability to use the Desktop Cube or Flipper extension to animate the workspace switch.
> [desktop-scroller@ccadeptic23] V2.2 Add Desktop Cube & Flipper support

- workspace-scroller@ori/files/workspace-scroller@ori/extension.js
- workspace-scroller@ori/files/workspace-scroller@ori/metadata.json
- workspace-scroller@ori/files/workspace-scroller@ori/po/ca.po
- workspace-scroller@ori/files/workspace-scroller@ori/po/da.po
- workspace-scroller@ori/files/workspace-scroller@ori/po/de.po
- workspace-scroller@ori/files/workspace-scroller@ori/po/es.po
- workspace-scroller@ori/files/workspace-scroller@ori/po/fi.po
- workspace-scroller@ori/files/workspace-scroller@ori/po/hu.po
- workspace-scroller@ori/files/workspace-scroller@ori/po/it.po
- workspace-scroller@ori/files/workspace-scroller@ori/po/nl.po
- workspace-scroller@ori/files/workspace-scroller@ori/po/pt_BR.po
- workspace-scroller@ori/files/workspace-scroller@ori/po/ro.po
- workspace-scroller@ori/files/workspace-scroller@ori/po/ru.po
- workspace-scroller@ori/files/workspace-scroller@ori/po/sv.po
- workspace-scroller@ori/files/workspace-scroller@ori/po/tr.po
- workspace-scroller@ori/files/workspace-scroller@ori/po/workspace-scroller@ori.pot
- workspace-scroller@ori/files/workspace-scroller@ori/po/zh_CN.po
- workspace-scroller@ori/files/workspace-scroller@ori/settings-schema.json
Added the ability to use the Desktop Cube or Flipper extension to animate the workspace switch.
> [workspace-scroller@ori] V1.0.2 Add Desktop Cube & Flipper support

- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/extension.js
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/metadata.json
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/ca.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/da.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/es.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/eu.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/fr.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/hu.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/it.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/ko.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/nl.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/pt_BR.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/ro.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/ru.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/smart-panel@mohammad-sn.pot
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/sv.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/tr.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/uk.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/zh_CN.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/settings-schema.json
> [smart-panel@mohammad-sn] Fixes #850

- CinnamonBurnMyWindows@klangman/CHANGELOG.md
- CinnamonBurnMyWindows@klangman/README.md
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/6.2/extension.js
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/6.2/settings-schema.json
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/effects/MagicLamp.js
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/metadata.json
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/CinnamonBurnMyWindows@klangman.pot
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/ca.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/es.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/fi.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/fr.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/hu.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/nl.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/pt.po
- Fixed the Magic Lamp effect to address the window flashing on minimize problem.
- Fixed the problem where no effect is activated when using "Randomized" for the "Unminimize window effect".
- Improved the wording of the Magic Lamp "Type of effect" drop down menu items.
> [CinnamonBurnMyWindows@klangman] V1.0.0 Two Fixes

- BlurCinnamon@klangman/files/BlurCinnamon@klangman/po/fi.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/fi.po
- CinnamonMagicLamp@klangman/files/CinnamonMagicLamp@klangman/po/fi.po
- DesktopCube@yare/files/DesktopCube@yare/po/fi.po
- Flipper@connerdev/files/Flipper@connerdev/po/fi.po
- blur-overview@nailfarmer.nailfarmer.com/files/blur-overview@nailfarmer.nailfarmer.com/po/fi.po
- desktop-scroller@ccadeptic23/files/desktop-scroller@ccadeptic23/po/fi.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/fi.po
- workspace-scroller@ori/files/workspace-scroller@ori/po/fi.po
New language packs and improvements
> Finnish language pack

- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/extension.js
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/metadata.json
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/ca.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/da.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/es.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/eu.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/fi.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/fr.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/hu.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/it.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/ko.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/nl.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/pt_BR.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/ro.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/ru.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/smart-panel@mohammad-sn.pot
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/sv.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/tr.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/uk.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/zh_CN.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/settings-schema.json
> [smart-panel@mohammad-sn] Volume control

- ArrangementOfButtonsOnWindowTitleBar@claudiux/files/ArrangementOfButtonsOnWindowTitleBar@claudiux/CHANGELOG.md
- ArrangementOfButtonsOnWindowTitleBar@claudiux/files/ArrangementOfButtonsOnWindowTitleBar@claudiux/README.md
- ArrangementOfButtonsOnWindowTitleBar@claudiux/files/ArrangementOfButtonsOnWindowTitleBar@claudiux/extension.js
- ArrangementOfButtonsOnWindowTitleBar@claudiux/files/ArrangementOfButtonsOnWindowTitleBar@claudiux/metadata.json
- ArrangementOfButtonsOnWindowTitleBar@claudiux/files/ArrangementOfButtonsOnWindowTitleBar@claudiux/po/ArrangementOfButtonsOnWindowTitleBar@claudiux.pot
- ArrangementOfButtonsOnWindowTitleBar@claudiux/files/ArrangementOfButtonsOnWindowTitleBar@claudiux/po/es.po
- ArrangementOfButtonsOnWindowTitleBar@claudiux/files/ArrangementOfButtonsOnWindowTitleBar@claudiux/po/fr.po
- ArrangementOfButtonsOnWindowTitleBar@claudiux/files/ArrangementOfButtonsOnWindowTitleBar@claudiux/settings-schema.json
In Expert Mode, you can define the exact button layout you want. This allows you to modify the order of the buttons.
> v2.0.0: Add Expert Mode

- cinnamon-screenshot@hilyxx/README.md
- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/extension.js
- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/metadata.json
- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/overlay.js
- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/po/cinnamon-screenshot@hilyxx.pot
- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/po/fr.po
- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/preview.js
- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/screenshot.js
- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/settings-schema.json
- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/translation.js
- Fix issue with translations
- Keyboard shortcuts added for all 3 screen capture modes.
> Cinnamon-screenshot@hilyxx - Hotfix and enhancement

- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/editOverlay.js
- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/icons/succes-clipboard-symbolic.svg
- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/metadata.json
- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/overlay.js
- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/po/cinnamon-screenshot@hilyxx.pot
- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/po/es.po
- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/po/fr.po
- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/po/hu.po
- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/po/it.po
- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/po/nl.po
- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/po/pt_BR.po
- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/preview.js
- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/stylesheet.css
- Fix multi-monitor behavior
- Fix ESC key
- Minor visual improvements to the dialog boxes
> cinnamon-screenshot@hilyxx - v1.22

- ArrangementOfButtonsOnWindowTitleBar@claudiux/files/ArrangementOfButtonsOnWindowTitleBar@claudiux/po/ca.po
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/po/ca.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/ca.po
- DesktopCube@yare/files/DesktopCube@yare/po/ca.po
- Flipper@connerdev/files/Flipper@connerdev/po/ca.po
- NewWindowSettings@klangman/files/NewWindowSettings@klangman/po/ca.po
- cinnamon-screenshot@hilyxx/files/cinnamon-screenshot@hilyxx/po/ca.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/po/ca.po
Adds
* ArrangementOfButtonsOnWindowTitleBar@claudiux
* cinnamon-screenshot@hilyxx
* NewWindowSettings@klangman
Updates
* BlurCinnamon@klangman
* CinnamonBurnMyWindows@klangman
* DesktopCube@yare
* Flipper@connerdev
* smart-panel@mohammad-sn
> Add/Update Catalan translations
