linuxmint/cinnamon-spices-extensions

- 0dyseus@CinnamonMaximusFork/README.md
- 0dyseus@CinnamonMaximusFork/files/0dyseus@CinnamonMaximusFork/HELP.html
- 0dyseus@CinnamonMaximusFork/files/0dyseus@CinnamonMaximusFork/extension.js
- 0dyseus@CinnamonMaximusFork/files/0dyseus@CinnamonMaximusFork/metadata.json
- 0dyseus@CinnamonMaximusFork/files/0dyseus@CinnamonMaximusFork/po/0dyseus@CinnamonMaximusFork.pot
- 0dyseus@CinnamonMaximusFork/files/0dyseus@CinnamonMaximusFork/po/es.po
- 0dyseus@CinnamonMaximusFork/files/0dyseus@CinnamonMaximusFork/settings-schema.json
- Better handling of **Settings.BindingDirection**. Just to avoid surprises when that constant is removed on future versions of Cinnamon.
- Added option to handle invisible windows problem. On the original Maximus extension (by fmete) I changed one of the _MOTIF_WM_HINTS flags from 0x2 to 0x0 to avoid having a border at the top of a maximized window with its title bar removed. This was working perfectly fine until Cinnamon 3.4. On Cinnamon 3.4, setting that flag to 0x0 would result on windows that started maximized and with their title bars removed to become invisible. I simply added an option for people using Cinnamon 3.4 or greater to change that flag.
- Redesigned the creation of the help file to be "on-line friendly".
- Finally fixed the annoyance of having titles on the help files …
> Cinnamon Maximus (Fork by Odyseus) (0dyseus@CinnamonMaximusFork) update

- 0dyseus@MultiTranslatorExtension/README.md
- 0dyseus@MultiTranslatorExtension/files/0dyseus@MultiTranslatorExtension/HELP.html
- 0dyseus@MultiTranslatorExtension/files/0dyseus@MultiTranslatorExtension/metadata.json
- 0dyseus@MultiTranslatorExtension/files/0dyseus@MultiTranslatorExtension/po/0dyseus@MultiTranslatorExtension.pot
- 0dyseus@MultiTranslatorExtension/files/0dyseus@MultiTranslatorExtension/po/da.po
- Added Danish localization. Thanks to [Alan01](https://github.com/Alan01).
- Redesigned the creation of the help file to be "on-line friendly".
- Finally fixed the annoyance of having titles on the help files hidden behind the top navigation bar when clicking the navigation links (Help/Contributors/Changelog).
- Fixed the display of a translated sentence on the help files that was being displayed untranslated.
- Added smooth scrolling for the links on the navigation bar of the help files.
- Updated localization template, localizations and help file due to changes to the *help file creator* script.
- Added to the xlet README file links to the localized help file.
> Multi Translator (0dyseus@MultiTranslatorExtension) update

- 0dyseus@WindowDemandsAttentionBehavior/README.md
- 0dyseus@WindowDemandsAttentionBehavior/files/0dyseus@WindowDemandsAttentionBehavior/HELP.html
- 0dyseus@WindowDemandsAttentionBehavior/files/0dyseus@WindowDemandsAttentionBehavior/extension.js
- 0dyseus@WindowDemandsAttentionBehavior/files/0dyseus@WindowDemandsAttentionBehavior/metadata.json
- 0dyseus@WindowDemandsAttentionBehavior/files/0dyseus@WindowDemandsAttentionBehavior/po/0dyseus@WindowDemandsAttentionBehavior.pot
- 0dyseus@WindowDemandsAttentionBehavior/files/0dyseus@WindowDemandsAttentionBehavior/po/da.po
- 0dyseus@WindowDemandsAttentionBehavior/files/0dyseus@WindowDemandsAttentionBehavior/settings-schema.json
- Better handling of **Settings.BindingDirection**. Just to avoid surprises when that constant is removed on future versions of Cinnamon.
- Added Danish localization. Thanks to [Alan01](https://github.com/Alan01).
- Redesigned the creation of the help file to be "on-line friendly".
- Finally fixed the annoyance of having titles on the help files hidden behind the top navigation bar when clicking the navigation links (Help/Contributors/Changelog).
- Fixed the display of a translated sentence on the help files that was being displayed untranslated.
- Added smooth scrolling for the links on the navigation bar of the help files.
- Updated localization template, localizations and help file due to changes to the *help file creator* script.
- Added to the xlet README file links to the localized …
> Window demands attention behavior (0dyseus@WindowDemandsAttentionBehavior) update

- .github/CODEOWNERS
- DesktopCube@yare/info.json
- Flipper@connerdev/info.json
- blur-overview@nailfarmer.nailfarmer.com/info.json
- cinnamon-maximus@fmete/info.json
- desktop-scroller@ccadeptic23/info.json
- gTile@shuairan/info.json
- opacify@anish.org/info.json
- workspace-scroller@ori/info.json
@yare @ConnerHansen @fmete @ccadeptic23 @shuairan @AnishN @ori
Set authors of abandoned applets to `Update`
none CODEOWNERS
[DesktopCube@yare](https://cinnamon-spices.linuxmint.com/extensions/view/27)
[Flipper@connerdev](https://cinnamon-spices.linuxmint.com/extensions/view/36)
[blur-overview@nailfarmer.nailfarmer.com](https://cinnamon-spices.linuxmint.com/extensions/view/14)
[cinnamon-maximus@fmete](https://cinnamon-spices.linuxmint.com/extensions/view/29)
[desktop-scroller@ccadeptic23](https://cinnamon-spices.linuxmint.com/extensions/view/17)
[gTile@shuairan](https://cinnamon-spices.linuxmint.com/extensions/view/21)
[opacify@anish.org](https://cinnamon-spices.linuxmint.com/extensions/view/25)
[workspace-scroller@ori](https://cinnamon-spices.linuxmint.com/extensions/view/38)
> 8 extensions: set authors to none

- watermark@germanfr/files/watermark@germanfr/extension.js
Changelog at: https://github.com/germanfr/watermark-cinnamon/commits/master
Sorry for PRing again. I didn't notice this until you merged the previous PR and I realized that the execution permission of files is not present after downloading from the spices. This is needed in order to detect the distribution to show it's logo by default.
> Update Watermark v3.6 (watermark@germanfr)

- gTile@shuairan/files/gTile@shuairan/extension.js
The gTile grid popup is supposed to be centered on top of the currently
focused window. The according conditions are always false because of a
type mismatch: window.get_monitor() returns a number while a for/in loop
iterator is a string.
> gTile@shuairan: Center grid in focused window

- gTile@shuairan/files/gTile@shuairan/extension.js
Windows that are tiled or snapped by the Muffin window manager can't be
resized or moved. Reset the tile mode before resizing the window.
> gTile@shuairan: Reset tile mode before resizing window

- DesktopCube@yare/files/DesktopCube@yare/extension.js
Main.layoutManager.bottomMonitor is obsolete. Replaced with Main.layoutManager.primaryMonitor.
> DesktopCube@yare - Make compatible w. Cinnamon 4.0

- Win7AltTab@entelechy/files/Win7AltTab@entelechy/extension.js
Will show windows from all workspaces if this setting is active on Cinnamon (Settings > Windows > Alt+Tab > Show windows from all workspaces)
I don't know who to mention as the author, because I couldn't find @entelechy on Github, sorry about that.
> [Win7AltTab@entelechy] Enable showing windows from all workspaces

- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/extension.js
- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/metadata.json
Current version of the maximus uses the compex way to determine the identificator of XWindow, including calls of `spawn_command_line_sync()` function. From version 2.4 of the muffin there is a suitable `get_xwindow()` method. Now we can use it. It's more simple and safe. Also it removes the warning of usage of unsafe functions.
The `_GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED` hint has been removed several months ago from the mutter, so better don't use it now to avoid unexpected behavior in future version.
Also there are code style improvements like usage of double quotes for strings, more clear variable names etc.
Last patch removes outdated comments.
> cinnamon-maximus@fmete: remove some hacks

- gTile@shuairan/files/gTile@shuairan/metadata.json
Tested with Cinnamon 4.2.4 in Fedora 30. Can't reproduce the issues mentioned in #220.
> gTile@shuairan: Add Cinnamon 4.2 to compatibility list

- gTile@shuairan/files/gTile@shuairan/metadata.json
Successfully tested with Cinnamon 4.4.2 in Fedora 30.
> gTile@shuairan: Add Cinnamon 4.4 to compatibility list

- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/extension.js
- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/settings-schema.json
1. add toggle decoration hotkey settings (<super>+u by default)
2. add setting to enable the logging
3. improve indentations of the settings-schema.json
4. fix the typo in the comment
5. settings initialization in alphabet order
> cinnamon-maximus@fmete: hotkey to toggle decoration of active window

- Win7AltTab@entelechy/files/Win7AltTab@entelechy/extension.js
The alt tab Thumbnail size is scaled from 0.09 to 0.18 to make it more useful .
> Increase the alt-tab thumbnail size

- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/extension.js
- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/metadata.json
- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/settings-schema.json
Various improvements:
1. Fix the undecorating of half-maximized windows (#277)
2. Remove the code related with usage of  `_GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED`, that has been disabled some time ago.
3. List of ignored applications is translating to regular expression. It brings the partial-match and case-insensitive.
4. Fix the spelling of 'maximize'. The API uses this spelling, so bring it to uniformity.
5. Small code improvements like function renames.
6. Actualize the comments
7. Add the version string into the metadata.
> cinnamon-maximus@fmete: various improvements and fixes

- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/metadata.json
Due the `last-edited` attribute the `about` message box wasn't being shown. Removed.
Also actualize the `url` info.
> cinnamon-maximus@fmete: fix the metadata

- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/extension.js
- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/metadata.json
If a window has been undecorated by hotkey, we shouldn't decorate it after resizing or moving.
> cinnamon-maximus@fmete: keep windows undecorated

- gTile@shuairan/files/gTile@shuairan/po/da.po
- gTile@shuairan/files/gTile@shuairan/po/gTile@shuairan.pot
- gTile@shuairan/files/gTile@shuairan/po/hu.po
- gTile@shuairan/files/gTile@shuairan/po/it.po
- gTile@shuairan/files/gTile@shuairan/po/sv.po
- gTile@shuairan/files/gTile@shuairan/po/tr.po
- gTile@shuairan/files/gTile@shuairan/po/zh_CN.po
- gTile@shuairan/files/gTile@shuairan/settings-schema.json
The original settings dialog had the entries for `Animiation` and `Auto-Close` immediately after the 4th button – without spacings or a heading:
- Move those two settings near the top under their own heading `Behavior`.
- Also move the two settings `lastGridCols` and `lastGridRows`, to the very first place (but since they are not shown, that does not change the layout of the settings dialog).
@veryangryman 
@jaszhix
> gTile@shuairan: Change layout in settings dialog

- gTile@shuairan/files/gTile@shuairan/extension.js
Fixes #291
In order to tile a window to an area consisting of a single tile, prior to this change, one would have to navigate to a tile using the arrow keys, press shift and an arrow key to begin a multi-tile area, followed by shift and the arrow key of the opposite direction to reduce the area again to a single tile, and then press space or enter to tile the window. Without the intermediate step of shift-arrow back and forth, the space and enter keys would not be registered as hotkeys but sent to the focused window instead where they would result in accidental input as described in issue #291.
It's a quick fix, but it seems to be working well for me.
> gTile@shuairan: Making Space and Enter work for single tile areas

- gTile@shuairan/files/gTile@shuairan/extension.js
The positioning code needs to account for client-decorated window padding for shadows.
> gTile@shuairan: Fix gtile csd handling

- rnbdsh@negateWindow/files/rnbdsh@negateWindow/extension.js
- rnbdsh@negateWindow/files/rnbdsh@negateWindow/metadata.json
Same change as in https://github.com/maiself/gnome-shell-extension-invert-color/commit/0e70aae1671c4fe4a5b42392fc588e1e5cd6f259
Proof that it works for me:
Feel free to also adapt other changes that have been on the gnome extension in the meanwhile, like stacking multiple invert effects on each other.
> Adapt to clutter having paint-context now (invert window extension)

- transparent-panels@germanfr/files/transparent-panels@germanfr/metadata.json
- transparent-panels@germanfr/files/transparent-panels@germanfr/policies.js
* Fixes #394
* Fixes #396 (duplicate)
Tested only on 5.4, the version check is supposed to work for earlier versions but you should have a look. I suspect it's going to work fine on the earlier versions.
@germanfr 
@brownsr This PR is now ready
> transparent-panels@germanfr: Fix for 5.4

- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/extension.js
With current version of cinnamon (5.4.12) when setting "Undecorate when tile" is on error will be thrown in .xsession-errors file:
```
Gjs-Message: 23:09:05.183: JS LOG: [LookingGlass/error] [Error: No signal 'tile' on object 'CinnamonWM']: Failed to evaluate 'enable' function on extension: cinnamon-maximus@fmete
```
Tile signal is no longer present and was moved to size-change signal as a param.
This PR should be mostly backwards compatible.
> cinnamon-maximus@fmete: Fix undecorate when tile

- opacify@anish.org/files/opacify@anish.org/extension.js
- Use `window.set_opacity()` instead of `window.get_compositor_private().opacity` which produces bad results - fixes #417
- After release, restore the window to its original opacity instead of 100% every time
Note that users can set opacity manually by setting System Settings -> Windows -> Action on title bar with mouse scroll: Adjust opacity (or soon with my WIP extension: https://github.com/NeatNit/cinnamon-opacity-slider). The previous (broken) code did not interfere with this setting as it changed the opacity in a different 'layer', but this PR modifies the same opacity, so must restore it at the end.
I am contemplating taking ownership of this extension, as I see it's currently set to `author: none` - any feedback on that?
> opacify@anish.org - bug fix and minor improvements

- cinnamon-maximus@fmete/files/cinnamon-maximus@fmete/extension.js
this covers the case when window is maximized by dragging it to the top (="tiled" to both sides)
`undecorateTile` setting should only affect half-maximized windows (which is checked inside `onMaximize` anyway - see `shouldAffect` function)
> cinnamon-maximus@fmete: Undecorate window if it's fully maximized

- gTile@shuairan/files/gTile@shuairan/5.4/gTile.js
- gTile@shuairan/src/5_4/package-lock.json
- gTile@shuairan/src/5_4/package.json
- gTile@shuairan/src/5_4/utils.ts
gTile would resize but now move the terminal as described in #425
The metaWindow documentation for [move_resize_frame](https://gnome.pages.gitlab.gnome.org/mutter/meta/method.Window.move_resize_frame.html) describes this as a resize call.  Moving after resizing seems to work for most the windows but not the terminal (which only seems to resize but not move). 
By adding the move_frame call directly afterwards, this forces moving the terminal after the resize.
This seems to be more of an issue with the Meta api.  but this seems to work as a workaround solution
> gTile@shuairan: fix terminal won't move after resize

- transparent-panels@germanfr/files/transparent-panels@germanfr/extension.js
When adding or removing a new monitor the state of the extension resets/removes the panel transparency, now it will update the state of the panel a guarantee that the panel continues with the transparency.
cc @germanfr
> transparent-panels@germanfr: update state when a new monitor is added or removed

- cinnamon-dynamic-wallpaper@TobiZog/files/cinnamon-dynamic-wallpaper@TobiZog/po/cinnamon-dynamic-wallpaper@TobiZog.pot
> cinnamon-dynamic-wallpaper@TobiZog: Add translation template

- focus-new-window@mdpenguin/files/focus-new-window@mdpenguin/extension.js
- focus-new-window@mdpenguin/files/focus-new-window@mdpenguin/metadata.json
Raise and focus the new window instead of activating it in focus-new-window@mdpenguin.
This addresses the issue described in https://github.com/linuxmint/cinnamon/issues/12269 where the new window demands attention even though it is already focused.
> Address persistent demands-attention issue in focus-new-window@mdpenguin

- opacity-slider@neatnit/files/opacity-slider@neatnit/metadata.json
I just upgraded to Linux Mint 22 and confirmed it works fine.
Is this metadata used for anything? I checked a few other extensions and they don't seem to keep this list updated.
Also, I don't know if this extension works on versions before 5.6. Does this prevent people from even trying? (Assuming there even are people using earlier Cinnamon versions today)
> Update opacity-slider@neatnit supports cinnamon version 6.2

- DesktopCube@yare/CHANGELOG.md
- DesktopCube@yare/README.md
- DesktopCube@yare/files/DesktopCube@yare/5.4/extension.js
- DesktopCube@yare/files/DesktopCube@yare/5.4/settings-schema.json
- DesktopCube@yare/files/DesktopCube@yare/metadata.json
- DesktopCube@yare/files/DesktopCube@yare/po/DesktopCube@yare.pot
- DesktopCube@yare/files/DesktopCube@yare/po/ca.po
- DesktopCube@yare/files/DesktopCube@yare/po/da.po
- DesktopCube@yare/files/DesktopCube@yare/po/de.po
- DesktopCube@yare/files/DesktopCube@yare/po/es.po
- DesktopCube@yare/files/DesktopCube@yare/po/eu.po
- DesktopCube@yare/files/DesktopCube@yare/po/fr.po
- DesktopCube@yare/files/DesktopCube@yare/po/hr.po
- DesktopCube@yare/files/DesktopCube@yare/po/hu.po
- DesktopCube@yare/files/DesktopCube@yare/po/it.po
- DesktopCube@yare/files/DesktopCube@yare/po/nl.po
- DesktopCube@yare/files/DesktopCube@yare/po/pt_BR.po
- DesktopCube@yare/files/DesktopCube@yare/po/ro.po
- DesktopCube@yare/files/DesktopCube@yare/po/ru.po
- DesktopCube@yare/files/DesktopCube@yare/po/tr.po
- DesktopCube@yare/files/DesktopCube@yare/po/zh_CN.po
- DesktopCube@yare/info.json
1. Added an option to remove the panels from the animation effect
2. Fix the Effect Setting options that were broken when the "tween" option widget was removed starting with cinnamon 5.4
3. Allow Cinnamon to play the workspace switch sound if it is enabled
4. Change info.json author to me, since there is currently no maintainer
> [DesktopCube@yare] Version 1.0.3

- CinnamonMagicLamp@klangman/CHANGELOG.md
- CinnamonMagicLamp@klangman/README.md
- CinnamonMagicLamp@klangman/files/CinnamonMagicLamp@klangman/5.6/ShouldAnimateManager.js
- CinnamonMagicLamp@klangman/files/CinnamonMagicLamp@klangman/5.6/extension.js
- CinnamonMagicLamp@klangman/files/CinnamonMagicLamp@klangman/5.6/settings-schema.json
- CinnamonMagicLamp@klangman/files/CinnamonMagicLamp@klangman/metadata.json
- CinnamonMagicLamp@klangman/files/CinnamonMagicLamp@klangman/po/CinnamonMagicLamp@klangman.pot
- CinnamonMagicLamp@klangman/files/CinnamonMagicLamp@klangman/po/ca.po
- CinnamonMagicLamp@klangman/files/CinnamonMagicLamp@klangman/po/es.po
- CinnamonMagicLamp@klangman/files/CinnamonMagicLamp@klangman/po/pt.po
Use _shouldAnimate() patching to prevent Cinnamon from animating the Minimize and Unminimize events. This means that users no longer need to disable the Effect settings in Cinnamon manually. Also means that the Cinnamon New Window animation can be enabled and active along with Magic Lap effects (so you don't have to give up new window fade in effects in order to enable Magic Lamp).
This change introduces a class to manage patching _shouldAnimate(). My next extension will also need to patch _shouldAnimate() so I needed a way to coordinate the patching so that the two extensions can coexist. The ShouldAnimateManager class will be used in both extensions. This class will manage the patching of _shouldAnimate() and allow both extensions to intercept different calling contexts of …
> [CinnamonMagicLamp@klangman] Remove the need to change Effect settings

- Flipper@connerdev/CHANGELOG.md
- Flipper@connerdev/files/Flipper@connerdev/5.4/extension.js
- Flipper@connerdev/files/Flipper@connerdev/metadata.json
1. Added code to make the animation performance better.
2. Replaced usage of Actor.scale_center_[x/y] with actor.set_pivot_point().
> [Flipper@connerdev] Improve animation and replace some deprecated api's

- CinnamonBurnMyWindows@klangman/CHANGELOG.md
- CinnamonBurnMyWindows@klangman/README.md
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/6.2/ShouldAnimateManager.js
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/6.2/extension.js
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/6.2/settings-schema.json
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/metadata.json
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/CinnamonBurnMyWindows@klangman.pot
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/ca.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/es.po
1. Added application specific effect settings that override the default effects setting when a specific application window is opened/closed
2. Added a "none" options to the effect drop-down lists which will perform no effect and allow the cinnamon default effect to apply
3. Added a button in the General configuration tab which will add an "Application Specific Settings" table entry for the application of the window that last had the focused.
> [CinnamonBurnMyWindows@klangman] App specific setting & "none" option

- compiz-windows-effect@hermes83.github.com/files/compiz-windows-effect@hermes83.github.com/extension.js
1. Fixed a bug in the disable() method where 'this' is not defined resulting in a failure to properly clean up after disabling the extension.
2. Fixed the class register so that it uses a random number in the name to avoid a failure if the extension is re-enabled without a cinnamon restart.
> [compiz-windows-effect@hermes83.github.com] Fix two bugs

- mouse-click-effects@anaximeno/files/mouse-click-effects@anaximeno/5.4/constants.js
- mouse-click-effects@anaximeno/files/mouse-click-effects@anaximeno/5.4/extension.js
- mouse-click-effects@anaximeno/files/mouse-click-effects@anaximeno/5.4/helpers.js
- mouse-click-effects@anaximeno/files/mouse-click-effects@anaximeno/5.4/mouseMovementTracker.js
- mouse-click-effects@anaximeno/files/mouse-click-effects@anaximeno/5.4/settings-schema.json
- mouse-click-effects@anaximeno/files/mouse-click-effects@anaximeno/metadata.json
- mouse-click-effects@anaximeno/files/mouse-click-effects@anaximeno/po/ca.po
- mouse-click-effects@anaximeno/files/mouse-click-effects@anaximeno/po/es.po
- mouse-click-effects@anaximeno/files/mouse-click-effects@anaximeno/po/eu.po
- mouse-click-effects@anaximeno/files/mouse-click-effects@anaximeno/po/hu.po
- mouse-click-effects@anaximeno/files/mouse-click-effects@anaximeno/po/mouse-click-effects@anaximeno.pot
- mouse-click-effects@anaximeno/files/mouse-click-effects@anaximeno/po/nl.po
- mouse-click-effects@anaximeno/files/mouse-click-effects@anaximeno/po/pt.po
- mouse-click-effects@anaximeno/files/mouse-click-effects@anaximeno/po/zh_CN.po
Suppress unnecessary logs in production and fix typo in settings
> mouse-click-effects@anaximeno: Version 1.0.2

- Flipper@connerdev/CHANGELOG.md
- Flipper@connerdev/README.md
- Flipper@connerdev/files/Flipper@connerdev/5.4/extension.js
- Flipper@connerdev/files/Flipper@connerdev/5.4/settings-schema.json
- Flipper@connerdev/files/Flipper@connerdev/metadata.json
1. Changed "dim_factor" to "opacity" since "dim_factor" is no longer defined
2. Stop setting "brightness" since it's no longer defined
3. Activate the new workspace on a change to avoid focus change errors
4. Changed the "Include Background" option default to true
> [Flipper@connerdev] Fix dimming and a few other minor changes

- slider@mohammad-sn/files/slider@mohammad-sn/extension.js
- slider@mohammad-sn/files/slider@mohammad-sn/po/ca.po
- slider@mohammad-sn/files/slider@mohammad-sn/po/da.po
- slider@mohammad-sn/files/slider@mohammad-sn/po/de.po
- slider@mohammad-sn/files/slider@mohammad-sn/po/es.po
- slider@mohammad-sn/files/slider@mohammad-sn/po/eu.po
- slider@mohammad-sn/files/slider@mohammad-sn/po/hu.po
- slider@mohammad-sn/files/slider@mohammad-sn/po/it.po
- slider@mohammad-sn/files/slider@mohammad-sn/po/nl.po
- slider@mohammad-sn/files/slider@mohammad-sn/po/pt_BR.po
- slider@mohammad-sn/files/slider@mohammad-sn/po/ro.po
- slider@mohammad-sn/files/slider@mohammad-sn/po/ru.po
- slider@mohammad-sn/files/slider@mohammad-sn/po/slider@mohammad-sn.pot
- slider@mohammad-sn/files/slider@mohammad-sn/po/zh_CN.po
This extension has been very broken for many years. The changes here just prevent the extension from breaking the desktop by refusing to operate when the cinnamon major version is 4 or higher. If the extension is ever fixed the code can be removed.
> [slider@mohammad-sn] Prevent loading in Cinnamon 4+

- CinnamonMagicLamp@klangman/CHANGELOG.md
- CinnamonMagicLamp@klangman/README.md
- CinnamonMagicLamp@klangman/files/CinnamonMagicLamp@klangman/5.6/ShouldAnimateManager.js
- CinnamonMagicLamp@klangman/files/CinnamonMagicLamp@klangman/metadata.json
The ShouldAnimateManager was failing to call the original Cinnamon _shouldAnimate() function for cases where the event context was not one that the manager is currently interested in. This meant that some Cinnamon's effects like maximize and restore (and maybe others) were failing to execute.
> [CinnamonMagicLamp@klangman] Fix for restore/maximize effects

- CinnamonBurnMyWindows@klangman/CHANGELOG.md
- CinnamonBurnMyWindows@klangman/README.md
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/6.2/ShouldAnimateManager.js
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/metadata.json
The ShouldAnimateManager was failing to call the original Cinnamon _shouldAnimate() function for cases where the event context was not one that the manager is currently interested in. This meant that some Cinnamon's effects like maximize and restore would apply even if the Cinnamon Effects settings had them disabled.
> [CinnamonBurnMyWindows@klangman] Fix for forcing Cinnamon effects on

- DesktopCube@yare/CHANGELOG.md
- DesktopCube@yare/README.md
- DesktopCube@yare/files/DesktopCube@yare/5.4/extension.js
- DesktopCube@yare/files/DesktopCube@yare/5.4/settings-schema.json
- DesktopCube@yare/files/DesktopCube@yare/metadata.json
- DesktopCube@yare/files/DesktopCube@yare/po/DesktopCube@yare.pot
- DesktopCube@yare/files/DesktopCube@yare/po/ca.po
- DesktopCube@yare/files/DesktopCube@yare/po/da.po
- DesktopCube@yare/files/DesktopCube@yare/po/de.po
- DesktopCube@yare/files/DesktopCube@yare/po/es.po
- DesktopCube@yare/files/DesktopCube@yare/po/eu.po
- DesktopCube@yare/files/DesktopCube@yare/po/fi.po
- DesktopCube@yare/files/DesktopCube@yare/po/fr.po
- DesktopCube@yare/files/DesktopCube@yare/po/hr.po
- DesktopCube@yare/files/DesktopCube@yare/po/hu.po
- DesktopCube@yare/files/DesktopCube@yare/po/it.po
- DesktopCube@yare/files/DesktopCube@yare/po/nl.po
- DesktopCube@yare/files/DesktopCube@yare/po/pt_BR.po
- DesktopCube@yare/files/DesktopCube@yare/po/ro.po
- DesktopCube@yare/files/DesktopCube@yare/po/ru.po
- DesktopCube@yare/files/DesktopCube@yare/po/tr.po
- DesktopCube@yare/files/DesktopCube@yare/po/zh_CN.po
1. Added ability to use Cube effect when changing the workspace via the "Workspace Switcher" applet
2. Added ability to use Cube effect when changing the workspace by activating a window on a different workspace
3. Added ability to use Cube effect when using the workspace "Direct Navigation" hotkeys
4. Enabled showing the desktop icons during the Cube effect
5. Allow the Cube to queue up hotkey press actions rather than ignoring hotkey presses during the Cube animation
6. Changed the "Animation duration" option to be a number of seconds (0.1 to 4 seconds)
7. Changed the Pullaway setting to be a "Cube size" as a percentage of the screen size
8. Added button to the Desktop Cube setting dialog which will launch the keyboard setting dialog as a convenient access to setting workspace related …
> [DesktopCube@yare] Version 2.0.0

- horizontal-osd@berk-karaal/files/horizontal-osd@berk-karaal/CustomOsd.js
- horizontal-osd@berk-karaal/files/horizontal-osd@berk-karaal/metadata.json
Hi @berk-karaal,
Thank you for this very useful extension!
With Cinnamon 6.4, the key "show-media-keys-osd" is no longer a string but a boolean and the " %" symbol is no longer displayed in OSD: https://github.com/linuxmint/mint22.1-beta/issues/4#issuecomment-2535973291
This PR corrects all that.
Regards.
Claudiux
> [horizontal-osd@berk-karaal] v0.0.3 - Improves compatibility with Cinnamon 6.4

- horizontal-osd@berk-karaal/info.json
Hi, I'm not able take care of the extension anymore. Glad that Cinnamon 6.4 features horizontal OSDs.
Linux Mint team can decide who will be next author or the status of the extension.
> [horizontal-osd@berk-karaal] set author to none

- Flipper@connerdev/CHANGELOG.md
- Flipper@connerdev/README.md
- Flipper@connerdev/files/Flipper@connerdev/5.4/extension.js
- Flipper@connerdev/files/Flipper@connerdev/5.4/settings-schema.json
- Flipper@connerdev/files/Flipper@connerdev/metadata.json
- Flipper@connerdev/files/Flipper@connerdev/po/Flipper@connerdev.pot
- Flipper@connerdev/files/Flipper@connerdev/po/ca.po
- Flipper@connerdev/files/Flipper@connerdev/po/da.po
- Flipper@connerdev/files/Flipper@connerdev/po/de.po
- Flipper@connerdev/files/Flipper@connerdev/po/es.po
- Flipper@connerdev/files/Flipper@connerdev/po/eu.po
- Flipper@connerdev/files/Flipper@connerdev/po/fi.po
- Flipper@connerdev/files/Flipper@connerdev/po/hu.po
- Flipper@connerdev/files/Flipper@connerdev/po/it.po
- Flipper@connerdev/files/Flipper@connerdev/po/nl.po
- Flipper@connerdev/files/Flipper@connerdev/po/pt_BR.po
- Flipper@connerdev/files/Flipper@connerdev/po/ro.po
- Flipper@connerdev/files/Flipper@connerdev/po/ru.po
- Flipper@connerdev/files/Flipper@connerdev/po/tr.po
- Flipper@connerdev/files/Flipper@connerdev/po/zh_CN.po
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/extension.js
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/metadata.json
- Added ability to use Flipper effects when changing the workspace via the "Workspace Switcher" applet
- Added ability to use Flipper effects when changing the workspace by activating a window on a different workspace
- Added ability to use Flipper effects when using the workspace "Direct Navigation" hotkeys
- Implement "Extension Workspace Switching API" used by smart-panel 1.4.2 to switch workspaces using the Flipper effect
- Added a configuration option to control if the "Workspace Switcher" applet will use the Flipper effect
- Added a configuration option to control if switching to a window on a different workspace will use the Flipper effect
- Use independent effect settings so each effect remembers it's own settings
- Added a "Randomized" effect option that will randomly select a …
> Flipper v2.0.0

- DesktopCube@yare/CHANGELOG.md
- DesktopCube@yare/README.md
- DesktopCube@yare/files/DesktopCube@yare/5.4/extension.js
- DesktopCube@yare/files/DesktopCube@yare/5.4/settings-schema.json
- DesktopCube@yare/files/DesktopCube@yare/metadata.json
- DesktopCube@yare/files/DesktopCube@yare/po/DesktopCube@yare.pot
- DesktopCube@yare/files/DesktopCube@yare/po/ca.po
- DesktopCube@yare/files/DesktopCube@yare/po/da.po
- DesktopCube@yare/files/DesktopCube@yare/po/de.po
- DesktopCube@yare/files/DesktopCube@yare/po/es.po
- DesktopCube@yare/files/DesktopCube@yare/po/eu.po
- DesktopCube@yare/files/DesktopCube@yare/po/fi.po
- DesktopCube@yare/files/DesktopCube@yare/po/fr.po
- DesktopCube@yare/files/DesktopCube@yare/po/hr.po
- DesktopCube@yare/files/DesktopCube@yare/po/hu.po
- DesktopCube@yare/files/DesktopCube@yare/po/it.po
- DesktopCube@yare/files/DesktopCube@yare/po/nl.po
- DesktopCube@yare/files/DesktopCube@yare/po/pt_BR.po
- DesktopCube@yare/files/DesktopCube@yare/po/ro.po
- DesktopCube@yare/files/DesktopCube@yare/po/ru.po
- DesktopCube@yare/files/DesktopCube@yare/po/tr.po
- DesktopCube@yare/files/DesktopCube@yare/po/zh_CN.po
- Added APIs used by the "Smart Panel" applet so it can use Desktop Cube in more cases
- Fixed a case where the Cube was used under the Expo (using the Left/Right arrow keys when the Expo was open). Using the Cube in this case was visually awkward and unnecessary so I disabled using Cube for this scenario
- Fixes issues when attempting to move a window to an adjacent workspace (Shift+Ctrl+Alt+Left/Right) for a window that is visible on all workspaces
> [DesktopCube@yare] Version 2.0.2

- DesktopCube@yare/files/DesktopCube@yare/5.4/extension.js
- DesktopCube@yare/files/DesktopCube@yare/metadata.json
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/extension.js
- smart-panel@mohammad-sn/files/smart-panel@mohammad-sn/metadata.json
Concerned extensions:
- smart-panel@mohammad-sn @mohammad-sn 
- DesktopCube@yare @klangman 
This PR prevents Cinnamon 6.4 from being frozen by critical errors whose messages flood `~/.xsession-errors`.
These errors can occur when Cinnamon starts up, but especially when it is restarted.
> Extensions: Fix critical errors

- CinnamonBurnMyWindows@klangman/CHANGELOG.md
- CinnamonBurnMyWindows@klangman/README.md
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/6.2/extension.js
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/6.2/settings-schema.json
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/metadata.json
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/CinnamonBurnMyWindows@klangman.pot
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/ca.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/es.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/fi.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/fr.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/hu.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/nl.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/pt.po
1. Added options in the configuration that allows you to define which effects will be used (if any) for dialog windows (i.e. a file open dialog). This allows you to use a more subtle or shorter running effect (i.e focus or glide) for all the dialog windows which are typically opened/closed more frequently.
2. Added support for using WM_CLASS names in the "application specific settings" table in the config.
3. Added two default "application specific settings" table entries for "VirtualBox" and "VirtualBoxVM. This addresses the Virtualbox issue described in the readme.md
> [CinnamonBurnMyWindows@klangman] 0.9.7 Add dialog specific fx options

- BlurCinnamon@klangman/CHANGELOG.md
- BlurCinnamon@klangman/README.md
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/6.0/extension.js
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/6.0/settings-schema.json
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/metadata.json
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/po/BlurCinnamon@klangman.pot
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/po/es.po
- Added the ability to apply different effects for every panel (or disable effects for some panels) based on the panel location and the monitor it is on
- Fixed the blur overlay animation for showing/hiding a panel when the panel is not set to "Always show panel"
- Simplify the settings: always show the dimming color but default to black giving a traditional dimming effect
- Added an option to prevent the extension from modifying the panel setting, so it it will only add a blur effect under the panel. This is useful when using a theme that is already transparent and you want the themes settings to remain
> [BlurCinnamon@klangman] V1.1.0 Unique panel effects / fixes

- BlurCinnamon@klangman/CHANGELOG.md
- BlurCinnamon@klangman/README.md
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/6.0/extension.js
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/6.0/settings-schema.json
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/metadata.json
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/po/BlurCinnamon@klangman.pot
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/po/es.po
- Added the ability (disabled by default) to apply effects to the Main Menu (menu@cinnamon.org)
- Improve the wording of several configuration options to make it more clear what they do
> [BlurCinnamon@klangman] Add Main Menu blurring option

- BlurCinnamon@klangman/CHANGELOG.md
- BlurCinnamon@klangman/README.md
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/6.0/extension.js
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/6.0/settings-schema.json
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/metadata.json
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/po/BlurCinnamon@klangman.pot
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/po/ca.po
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/po/es.po
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/po/fr.po
- Replaced the Main Menu effects with generic Popup Menu effects which covers the main menu as well as all other Applet popup menus.
- Added a Saturation option which allow you to desaturate the background overlay (0%, grey scale to 100%)
> [BlurCinnamon@klangman] Applet popup menu and desaturation support

- BlurCinnamon@klangman/CHANGELOG.md
- BlurCinnamon@klangman/README.md
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/6.0/extension.js
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/6.0/settings-schema.json
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/metadata.json
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/po/BlurCinnamon@klangman.pot
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/po/ca.po
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/po/es.po
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/po/fr.po
- BlurCinnamon@klangman/files/BlurCinnamon@klangman/po/nl.po
- Added the ability to apply effects to the Desktop background image (you can Dim, Blur and Desaturate, but currently you can't colorize the background image)
- Improved how the blur effect keeps in sync with the size of the the panels
- Always hid the parts of windows that are under the panels, even when no blur effect is need to be more consistent
- Several fixes , minor improvements, optimizations and simplifications to the code
> BlurCinnamon@klangman: Desktop background effect + fixes

- CinnamonBurnMyWindows@klangman/CHANGELOG.md
- CinnamonBurnMyWindows@klangman/README.md
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/6.2/CustomWidgets.py
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/6.2/extension.js
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/6.2/settings-schema.json
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/CinnamonBurnMyWindowsTest
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/CinnamonBurnMyWindowsTest.py
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/effects/Fire.js
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/metadata.json
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/CinnamonBurnMyWindows@klangman.pot
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/ca.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/es.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/fi.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/fr.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/hu.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/nl.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/pt.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/resources/shaders/fire.frag
- Added a "Reset to default" button for each effect under the "Effect Settings" tab.
- Added an "Open effect preview window" button to "Effect Settings" tab. It opens a preview window to test out the currently selected effect in the "Show setting for effect" drop down list.
- Added a custom "scale" widget that puts the label, scale, and number in a line to save GUI space. It also "marks" the default value for the setting.
- Fixed the issue where some setting under the "Effect Settings" were not appearing properly after changing the "Show settings for effect" drop-down. It turns out that adding a common element at the end of the effect settings somehow makes the issue disappear. So I didn't really "fix" anything but adding the "Open effect preview window" button at the bottom of the effect …
> [CinnamonBurnMyWindows@klangman] Version 0.9.9

- OsdWithNumber@JosephMcc/files/OsdWithNumber@JosephMcc/osdWithNumber.js
Thanks to @GabrielCamara3526 for the fix. Just cleaned up whitespace usage a bit.
https://github.com/linuxmint/cinnamon-spices-extensions/pull/857
> OsdWithNumber@JosephMcc: Hide percentage when it's not needed

- CinnamonBurnMyWindows@klangman/CHANGELOG.md
- CinnamonBurnMyWindows@klangman/README.md
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/6.2/CustomWidgets.py
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/6.2/extension.js
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/6.2/settings-schema.json
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/effects/Fire.js
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/effects/MagicLamp.js
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/effects/Mushroom.js
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/metadata.json
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/CinnamonBurnMyWindows@klangman.pot
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/ca.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/es.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/fi.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/fr.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/hu.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/nl.po
- CinnamonBurnMyWindows@klangman/files/CinnamonBurnMyWindows@klangman/po/pt.po
- Fix Fire and Mushroom effect presets when using a translation of Burn-My-Windows. Note: This fix will reset the prefix settings to default so you will need to reconfigure the extension to use your desired preset if you had previously setup a preset other then the default one.
- Added "Open/Close Edge" and "Open/Close Offset" options under the Magic Lamp effect settings. These options allow you to set the monitor edge location where the Magic Lamp effect will animate from/to for open and close events. The default will be the "Closest edge to mouse pointer" but you can set it to a specific edge and offset. For example, you could direct the animations to towards the Main Menu location. These options only apply to Open/Close events as the minimize/unminimize events will continue to use the …
> [CinnamonBurnMyWindows@klangman] V1.0.1 Fix for translated presets

- Flipper@connerdev/CHANGELOG.md
- Flipper@connerdev/README.md
- Flipper@connerdev/files/Flipper@connerdev/5.4/extension.js
- Flipper@connerdev/files/Flipper@connerdev/5.4/settings-schema.json
- Flipper@connerdev/files/Flipper@connerdev/metadata.json
- Flipper@connerdev/files/Flipper@connerdev/po/Flipper@connerdev.pot
- Flipper@connerdev/files/Flipper@connerdev/po/ca.po
- Flipper@connerdev/files/Flipper@connerdev/po/da.po
- Flipper@connerdev/files/Flipper@connerdev/po/de.po
- Flipper@connerdev/files/Flipper@connerdev/po/es.po
- Flipper@connerdev/files/Flipper@connerdev/po/eu.po
- Flipper@connerdev/files/Flipper@connerdev/po/fi.po
- Flipper@connerdev/files/Flipper@connerdev/po/fr.po
- Flipper@connerdev/files/Flipper@connerdev/po/hu.po
- Flipper@connerdev/files/Flipper@connerdev/po/it.po
- Flipper@connerdev/files/Flipper@connerdev/po/nl.po
- Flipper@connerdev/files/Flipper@connerdev/po/pt_BR.po
- Flipper@connerdev/files/Flipper@connerdev/po/ro.po
- Flipper@connerdev/files/Flipper@connerdev/po/ru.po
- Flipper@connerdev/files/Flipper@connerdev/po/tr.po
- Flipper@connerdev/files/Flipper@connerdev/po/zh_CN.po
- Added a Disable effect option which will use no workspace switch effect, not even the default Cinnamon workspace switch effect. Since Cinnamon does not offer a way to independently disable the workspace switch effect, with this option you can disable the effect but still allow of the desktop and window effects.
- Fixed the disappearing effect settings problem using a "hack" fix. Adding a permanent empty label field below the effect settings avoids the issue.
> [Flipper@connerdev] V2.0.2 Disabled option + Fix

- gTile@shuairan/README.md
- gTile@shuairan/files/gTile@shuairan/5.4/gTile.js
- gTile@shuairan/files/gTile@shuairan/5.4/settings-schema.json
- gTile@shuairan/files/gTile@shuairan/5.4/stylesheet.css
@sphh - are you still handling PRs?
This pull request has a bug fix and a new feature.
1. Issue #444: the hotkey stops working after monitor wakes up from sleep. Simply switching the monitor off and on reproduced the problem for me. This PR fixes the issue.
2. I've adopted [Gnome Tactile](https://extensions.gnome.org/extension/4548/tactile/) feature. If _Show tile labels_ is enabled in Settings > Behaviour, lowercase letters are shown on each tile. Selecting two letters places the active window into the space. The two letters correspond to the top left and bottom right rectangle to place the active window. If the same letter is pressed twice, the active window goes into that tile, which is what #906 requested. If more than 26 tiles are visible, uppercase letters are shown. So a-z is shown …
> gTile@shuairan: hotkey fix, add Gnome Tactile-like feature
